sudo: required
services:
    - docker

before_install:
  - docker build -t krazymir/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true krazymir/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-730503576789"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key:
    secure: "$AWS_KEY"

  notifications:
    webhooks: https://outlook.office.com/webhook/74b2da1b-0e91-4cd5-b7f7-5e1d134848c9@204cb148-e6fd-421f-825f-cabf6a4a4a55/TravisCI/921cb147d34440f2a698507766458927/035d09a8-0490-49f2-ab77-7a7a55b340b0