sudo: required
services:
    - docker

before_install:
  - docker build -t krazymir/react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true krazymir/react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-central-1-730503576789"
  bucket_path: "Docker-react"
  on:
    branch: master
  access_key_id: $AWS_ID
  secret_access_key:
    secure: "$AWS_KEY"